### PR TITLE
Mp handler

### LINKED ISSUE #43: Adding multipart encoding for uploads and refactor content-type
ToDos in Interpreter:
- parse `content-type` field in request header:
 - If not `text/plain` or `multipart/form-data`, set 415 `UNSUPPORTED MEDIA-TYPE` http status code
 - If `delimiter` is given, check if its less then 70 characters long. Else give `INVALID REQUEST` http status code.
 - The entry `charset` can be ignored
 - Check if `content-length` agrees with the length of the request content (already implemented I guess)
 - In case of `multipart/form-data`, a delimiter needs to be given

ToDos in Executor:
- For `multipart/form-data`:
 - Check if the blocks are written correctly: Every block 
  - needs to be seperated by the delimiter
  - must have a `Content-Disposition: form-data; name=<control-name>` header
  - can have a `filename=<filename>` definition and a header `Content-type`
  - If something goes wrong, an error is send and the server needs to be cleaned up
  - Headers and content are separated by `\r\n`

### PR DESCRIPTION
**Pull request by Finanzcreeper**
implemented multipart

### CODE REVIEW

File: interpreters/httpInterpreter.cpp [hunk 1]
```diff
@@ -21,10 +21,124 @@ void interpretRequest(Request& request, const t_server& settings) {
...
+		return;
+	}
+
+	unsigned long length = std::atoi(lt->second.c_str());
+	if (length != request.Body.size()) {
+///*			*/std::cout << request.Body.size() << std::endl;
+		request.RequestIntegrity = BAD_REQUEST;
+		return;
+	}
+
```
Comment (hoeftint) [inline interpreters/httpInterpreter.cpp:59]: end delimiter check

**Review by hoeftint — APPROVED** [review]
Approved
